model_name_or_path: Qwen/Qwen2-0.5B-Instruct
model_name: Qwen2-0.5B-Instruct
model_config:
  _target_: trl.ModelConfig
  model_revision: main
  torch_dtype: bfloat16
  attn_implementation: flash_attention_2